project_name: autoproofcli
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/autoproof/cli/cmd.cliVersion={{.Version}}

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of uname.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

nfpms:
  - formats:
      - deb
      - rpm
    vendor: autoproof.dev
    homepage: https://autoproof.dev
    maintainer: autoproof.dev

brews:
  - repository:
      owner: autoproof
      name: homebrew-autoproof
      branch: main
    name: autoproof
    homepage: "https://github.com/Autoproof/homebrew-autoproof"
    description: "command-line interface for automatic code & content protection"
    folder: Formula
    install: |
      bin.install "autoproofcli"

dockers:
  - image_templates:
      - "ghcr.io/autoproof/cli:{{ .Tag }}"
    dockerfile: ./Dockerfile.goreleaser
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"