# syntax=docker/dockerfile:1.3
FROM alpine:3.18
RUN addgroup --system autoproof && \
    adduser --system autoproof --ingroup autoproof
USER autoproof
ENTRYPOINT [ "/usr/local/bin/autoproofcli" ]
COPY autoproofcli /usr/local/bin/autoproofcli