name: Autoproof Snapshot
on:
  push:
    branches:
      - main
jobs:
  autoproof:
    runs-on: ubuntu-latest
    container: ghcr.io/autoproof/cli:v0.1.5
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Autoproof snapshot
        run: |
          autoproof snapshot -m "GHA on {{ github.sha }}"